# Generated by Django 4.2.2 on 2023-06-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personalprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified at', null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(validators=[personalprofile.models.Profile.validate_date_of_birth])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified at', null=True)),
                ('address_1', models.CharField(help_text='Address line 1', max_length=255, verbose_name='Street Address 1')),
                ('address_2', models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True, verbose_name='Street Address 2')),
                ('city', models.CharField(help_text='City', max_length=64)),
                ('postcode', models.CharField(help_text='Postcode', max_length=16, verbose_name='Postcode')),
                ('current', models.BooleanField(default=True, verbose_name='Current Address')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalprofile.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
